version: '3'
services:
  edwiges:
    build: .
    environment:
      - EDWIGES_PROVIDER_HOST
      - EDWIGES_PROVIDER_PORT
      - EDWIGES_PROVIDER_USERNAME
      - EDWIGES_PROVIDER_PASSWORD
    ports:
      - 465:465
      - 8888:8888
